---
version: '3.9'
services:
  weaviate-node-1:
    init: true
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:$WEAVIATE_NODE_1_VERSION
    ports:
    - 8080:8080
    - 6060:6060
    restart: on-failure:0
    environment:
      LOG_LEVEL: 'debug'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'backup-gcs'
      BACKUP_FILESYSTEM_PATH: '/var/lib/backups'
      CLUSTER_HOSTNAME: 'node1' 
      CLUSTER_GOSSIP_BIND_PORT: '7100'
      CLUSTER_DATA_BIND_PORT: '7101'
      GOOGLE_CLOUD_PROJECT: 'cluster-version-backup-test'
      STORAGE_EMULATOR_HOST: 'backup-gcs:9090' 
      BACKUP_GCS_ENDPOINT: 'backup-gcs:9090'
      BACKUP_GCS_BUCKET: 'weaviate-backups'

  # Mutually exclusive with weaviate-node-2
  # Used for single-node BRO version compat
  weaviate-backup-node:
    init: true
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8081'
    - --scheme
    - http
    image: semitechnologies/weaviate:$WEAVIATE_NODE_2_VERSION
    ports:
    - 8081:8081
    - 6061:6060
    restart: on-failure:0
    environment:
      LOG_LEVEL: 'debug'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'backup-gcs'
      BACKUP_FILESYSTEM_PATH: '/var/lib/backups'
      CLUSTER_HOSTNAME: 'node1' 
      GOOGLE_CLOUD_PROJECT: 'cluster-version-backup-test'
      STORAGE_EMULATOR_HOST: 'backup-gcs:9090' 
      BACKUP_GCS_ENDPOINT: 'backup-gcs:9090'
      BACKUP_GCS_BUCKET: 'weaviate-backups'

  # Mutually exclusive with weaviate-backup-node
  # Used for cluster backup scenarios
  weaviate-node-2:
    init: true
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8081'
    - --scheme
    - http
    image: semitechnologies/weaviate:$WEAVIATE_NODE_2_VERSION
    ports:
    - 8081:8081
    - 6061:6060
    restart: on-failure:0
    environment:
      LOG_LEVEL: 'debug'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'backup-gcs'
      BACKUP_FILESYSTEM_PATH: '/var/lib/backups'
      CLUSTER_HOSTNAME: 'node2' 
      CLUSTER_GOSSIP_BIND_PORT: '7102'
      CLUSTER_DATA_BIND_PORT: '7103'
      CLUSTER_JOIN: 'weaviate-node-1:7100'
      GOOGLE_CLOUD_PROJECT: 'cluster-version-backup-test'
      STORAGE_EMULATOR_HOST: 'backup-gcs:9090' 
      BACKUP_GCS_ENDPOINT: 'backup-gcs:9090'
      BACKUP_GCS_BUCKET: 'weaviate-backups'
    volumes:
    - ./data-node-2:/var/lib/weaviate

  backup-gcs:
    image: oittaa/gcp-storage-emulator
    command:
    - 'start'
    - '--host'
    - '0.0.0.0'
    - '--port'
    - '9090'
    - '--default-bucket'
    - 'weaviate-backups'
    - '--in-memory'
    ports:
    - '9090:9090'
...
